### ISSUE TITLE
getWinnings

### ISSUE THREAD

**Issue by ghost** [techwithtim/JavaScript-Slot-Machine#1]
When we select to gamble on 1 line and if we get the printRows as follows :-
[A | B | C ]
[D | D | D]
[B | C | A ]
We are still winning as we get one matching row but actually the result shows that we losing .

Basically we win only if the first line matches ,but actually we should win if any of the 3 lines matches .

**Comment by jeremiahomueti** [comment]
Hmm, true. When any of the three line matches, that should be a win.

**Comment by kushsriv** [comment]
> 

what's the fix for it?

**Comment by Yashu-777** [comment]
> > 
> 
> what's the fix for it?


The following changes to the getWinnings fucntion should solve the issue:

```
const getWinnings = (rows, bet, lines) => {
    let winnings = 0;
    const possibiliites=[];
    for (let row = 0; row < ROWS; row++) {
      const symbols = rows[row];
      let allSame = true;
      
      for (const symbol of symbols) {
        if (symbol != symbols[0]) {
          allSame = false;
          break;
        }
      }
  
      if (allSame) {
          possibiliites.push(bet * SYMBOL_VALUES[symbols[0]]);
      }
    }
    possibiliites.sort();
    possibiliites.reverse();
    for(let i=0;i<possibiliites.length;i++){
        if(i<lines) winnings+=possibiliites[i];
    }
    return winnings;
  };

```
